### ISSUE TITLE
GLTF models render incompletely

### ISSUE THREAD

**Issue by gijonc** [aalavandhaann/blueprint-js#24] opened 2019-04-09 16:31 UTC
I tried to put the GLTF loader code into the original [Blueprint3d](https://github.com/furnishup/blueprint3d) project, the program can render the model without errors but that appears like
<img width="390" alt="Screen Shot 2019-04-08 at 12 29 28" src="https://user-images.githubusercontent.com/13028235/55816980-58a93300-5aa8-11e9-9b76-6845adbd69b4.png">

obviously a part of the model is missing from the item. Yet, the problem does **NOT** appear in this project.
<img width="309" alt="Screen Shot 2019-04-09 at 09 24 10" src="https://user-images.githubusercontent.com/13028235/55817418-6317fc80-5aa9-11e9-9fc3-cb215dcc5da8.png">

I have tried to match the code between the original BP3D project with this project and I do not see any major difference between the two for the addItem part. So any of you may know the reason causing the problem?

**Comment by aalavandhaann** [comment] 2019-04-11 20:54
Duplicate of #23

**Closed by aalavandhaann** 2019-04-11 20:54 UTC
